name: my-second-action
on: push
jobs:
    lint:
        name: lint
        runs-on: ubuntu-22.04
        steps:
            - name: lint
              run: echo "linting..."
            - name: checkout
              uses: actions/checkout@v3
            - name: init npm
              run: npm ci
            - name: 'node lint'
              run: echo 'fake lint'
    test:
        name: test
        needs: lint
        runs-on: ubuntu-22.04
        steps:
            - name: test
              run: echo "testing..."
            - name: checkout
              uses: actions/checkout@v3
            - name: init npm
              run: npm ci
            - name: 'node test'
              run: echo "fake testing"
    deploy:
        name: deploy
        needs: test
        runs-on: ubuntu-22.04
        steps:
            - name: deploy
              run: echo "deploying..."
            - name: checkout
              uses: actions/checkout@v3
            - name: init npm
              run: npm ci
            - name: build
              run: npm run build
            - name: deploy
              run: echo "fake deploy!"

