name: echo issues event
on: issues
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
            - name: "hello"
              run: echo "hello there"
            - name: "echo event"
              run: echo "${{ toJSON(github.event)}}"
